"""Add RepoConversationSummary and UserFact models

Revision ID: 45a739ee4ac0
Revises: 9c96a7f0a9b6
Create Date: 2025-07-11 00:03:24.365079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a739ee4ac0'
down_revision = '9c96a7f0a9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_conversation_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('last_message_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data_source_id', name='_user_data_source_uc')
    )
    op.create_table('user_facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('fact_key', sa.String(length=255), nullable=False),
    sa.Column('fact_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fact_key', name='_user_fact_key_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_facts')
    op.drop_table('repo_conversation_summaries')
    # ### end Alembic commands ###
