"""Add timestamps to AdminUser model

Revision ID: 9c96a7f0a9b6
Revises: cea6f78f0a72
Create Date: 2025-07-02 01:09:14.473861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func # Import the func module


# revision identifiers, used by Alembic.
revision = '9c96a7f0a9b6'
down_revision = 'cea6f78f0a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=func.now(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=func.now(), onupdate=func.now(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
